"""Exact homology dimensions after identifying equal boundary columns at one grade.

Equality is up to sign, not arbitrary rescaling. Zero columns remain distinct.
The quotient is formed on sparse columns; rank uses the existing integer core
reduction. No harmonic basis, Gram matrix or spectral tolerance is introduced.
"""
from __future__ import annotations

from dataclasses import dataclass
from numbers import Integral

import numpy as np

from rexgraph.graded_boundary import _rank_integer_columns
from rexgraph.native_rank import clear_column_denominators, exact_tower, tower_chain_residual


@dataclass(frozen=True)
class HomologySplit:
    grade: int
    betti: int
    simple: int
    multiplicity: int
    chain_multiplicity: int
    quotient_size: int
    lower_rank: int
    upper_rank: int
    quotient_upper_rank: int
    rank_methods: tuple[str, ...]


def _column_quotient(columns):
    """Return representative indices and the signed sparse projection entries."""
    groups, keep, projection = {}, [], []
    for index, column in enumerate(columns):
        entries = sorted((row, value) for row, value in column.items() if value)
        sign = -1 if entries and entries[0][1] < 0 else 1
        key = tuple((row, value * sign) for row, value in entries)
        # Empty columns are independent zero boundary cells, not occurrences of
        # a shared nonzero boundary. Retain each one as the C1 API does.
        if not key or key not in groups:
            target = len(keep)
            keep.append(index)
            if key:
                groups[key] = (target, sign)
            projection.append((target, 1))
        else:
            target, representative_sign = groups[key]
            projection.append((target, sign * representative_sign))
    return keep, projection


def homology_split(rex, grade=1):
    """Dimensions of H_k(X/W) and ker(H_k(X) -> H_k(X/W)), over Q.

    W is generated by signed differences of nonzero B_k columns equal up to
    sign. Only C_k is collapsed; the adjacent upper map becomes pi B_(k+1).
    At C0 there is no lower map to group. Missing upper maps are exact zero.
    Filled multiplicity cycles are excluded from the homology reading.
    """
    if isinstance(grade, (bool, np.bool_)) or not isinstance(grade, Integral):
        raise TypeError("homology grade must be an integer")
    grade = int(grade)
    shapes, tower = exact_tower(rex)
    sizes = [shapes[0][0]] + [shape[1] for shape in shapes]
    if not 0 <= grade < len(sizes):
        raise ValueError(f"grade {grade} is not present")
    residual = tower_chain_residual(shapes, tower)
    if residual:
        raise ValueError(f"homology split requires the chain condition; exact residual = {residual}")

    methods = []

    def rank(shape, columns):
        if not any(columns):
            methods.append("exact-zero")
            return 0
        value, method = _rank_integer_columns(shape, clear_column_denominators(columns))
        methods.append(method)
        return value

    n = sizes[grade]
    if grade == 0:
        keep, projection, lower_rank = range(n), (), 0
    else:
        keep, projection = _column_quotient(tower[grade - 1])
        # Signed duplicate columns cannot change rank. Reduce representatives,
        # not every repeated occurrence, while composing the original tower.
        lower_rank = rank((shapes[grade - 1][0], len(keep)),
                          [tower[grade - 1][index] for index in keep])
    upper = tower[grade] if grade < len(tower) else []
    upper_rank = rank((n, len(upper)), upper)
    if len(keep) == n:
        quotient_rank = upper_rank
    else:
        projected = []
        for column in upper:
            target = {}
            for row, coefficient in column.items():
                new_row, sign = projection[row]
                target[new_row] = target.get(new_row, 0) + sign * coefficient
            projected.append({row: value for row, value in target.items() if value})
        quotient_rank = rank((len(keep), len(upper)), projected)
    betti = n - lower_rank - upper_rank
    simple = len(keep) - lower_rank - quotient_rank
    return HomologySplit(grade, betti, simple, betti - simple, n - len(keep),
                         len(keep), lower_rank, upper_rank, quotient_rank, tuple(methods))
