"""
OCR integration: unified client for multiple OCR backends.

Supports three OCR providers through a single adapter interface:

    1. **Unlimited-OCR / DeepSeek-OCR-2** (self-hosted GPU): connects
       to a running SGLang or OpenAI-compatible server.  Supports
       Baidu's Unlimited-OCR (Jun 2026), DeepSeek-OCR-2 (Jan 2026),
       and DeepSeek-OCR (Oct 2025) - all use the same protocol.

    2. **Mistral OCR** (cloud API): uses the ``mistralai`` SDK to
       call Mistral's ``mistral-ocr-latest`` model.  No GPU required,
       just a ``MISTRAL_API_KEY``.  Native PDF support (no conversion).

    3. **Offline stub**: when no server or API key is available,
       falls back to Tesseract OCR or returns empty results so the
       pipeline can still be tested.

Usage:

    from agent.integrations.unlimited_ocr import create_ocr_client

    # Auto-selects the best available backend
    client = create_ocr_client()
    text = client.ocr_image("scan.png")

    # Force a specific backend
    from agent.integrations.unlimited_ocr import (
        UnlimitedOCRClient,   # GPU server (Unlimited-OCR / DeepSeek)
        MistralOCRClient,      # Cloud API
    )
    client = UnlimitedOCRClient(server_url="http://gpu:10000")
    client = UnlimitedOCRClient.deepseek_ocr2(server_url="http://gpu:10000")
    client = MistralOCRClient(api_key="sk-...")
"""

from __future__ import annotations

import base64
import contextlib
import json
import logging
import os
import re
import shutil
import tempfile
import time
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Constants
DEFAULT_SERVER_URL = "http://127.0.0.1:10000"
DEFAULT_MODEL_NAME = "Unlimited-OCR"
DEFAULT_PROMPT = "document parsing."
DEFAULT_MULTI_PROMPT = "Multi page parsing."
DEFAULT_MAX_LENGTH = 32768
DEFAULT_NGRAM_SIZE = 35
DEFAULT_NGRAM_WINDOW = 128
DEFAULT_NGRAM_WINDOW_MULTI = 1024
DEFAULT_TEMPERATURE = 0
REQUEST_TIMEOUT = 1200
MAX_RETRIES = 3

IMAGE_EXTENSIONS = frozenset({
    ".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tiff", ".tif",
})
PDF_EXTENSIONS = frozenset({".pdf"})

# Data classes
@dataclass
class OCRResult:
    """Result of a single OCR operation.

    Attributes
    ----------
    text : str
        Extracted text (typically markdown-formatted).
    source : str
        Path of the source image or PDF page.
    page : int
        Page number (0 for single-image, 1-based for PDF pages).
    tokens : int
        Number of tokens generated by the model.
    elapsed : float
        Wall-clock time in seconds for this request.
    """

    text: str
    source: str = ""
    page: int = 0
    tokens: int = 0
    elapsed: float = 0.0


@dataclass
class OCRBatchResult:
    """Result of a multi-page or batch OCR operation.

    Attributes
    ----------
    pages : list of OCRResult
        Per-page OCR results, in order.
    full_text : str
        All page texts concatenated with page-break markers.
    source : str
        Original PDF or directory path.
    total_tokens : int
        Sum of tokens across all pages.
    total_elapsed : float
        Wall-clock time for the entire batch.
    """

    pages: list[OCRResult] = field(default_factory=list)
    source: str = ""
    total_tokens: int = 0
    total_elapsed: float = 0.0

    @property
    def full_text(self) -> str:
        parts = []
        for r in self.pages:
            if r.page > 0:
                parts.append(f"\n\n<!-- page {r.page} -->\n\n")
            parts.append(r.text)
        return "".join(parts).strip()

    @property
    def n_pages(self) -> int:
        return len(self.pages)


# Utilities
def _encode_image(image_path: str) -> dict[str, Any]:
    """Encode an image file as a base64 data-URL content block."""
    ext = os.path.splitext(image_path)[1].lower()
    mime_map = {
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
        ".webp": "image/webp",
        ".bmp": "image/bmp",
        ".tiff": "image/tiff",
        ".tif": "image/tiff",
    }
    mime = mime_map.get(ext, f"image/{ext.lstrip('.')}")
    with open(image_path, "rb") as f:
        data = base64.b64encode(f.read()).decode("utf-8")
    return {
        "type": "image_url",
        "image_url": {"url": f"data:{mime};base64,{data}"},
    }


def _pdf_to_images_worker(pdf_path: str, out_dir: str, dpi: int) -> int:
    """Convert PDF pages to PNG images.  Runs inside a subprocess.

    Returns the number of pages written.  Fitz (pymupdf) objects are
    allocated AND freed inside this function so that if the C-level
    cleanup segfaults it only kills the subprocess, not the server.
    """
    import fitz  # PyMuPDF
    doc = fitz.open(pdf_path)
    mat = fitz.Matrix(dpi / 72, dpi / 72)
    n = 0
    for i, page in enumerate(doc):
        out = os.path.join(out_dir, "page_%04d.png" % (i + 1))
        page.get_pixmap(matrix=mat).save(out)
        n += 1
    doc.close()
    return n


def _pdf_to_images(pdf_path: str, dpi: int = 300) -> list[str]:
    """Convert each PDF page to a PNG image.

    Requires PyMuPDF (``fitz``).  Returns a list of temporary
    image file paths in page order.

    Runs fitz in a subprocess to prevent GC segfaults when
    pymupdf and torch coexist in the same process.  If the
    subprocess crashes, this raises RuntimeError instead of
    taking down the server.
    """
    try:
        import fitz  # noqa: F401, check availability before spawning
    except ImportError:
        raise ImportError(
            "PyMuPDF is required for PDF processing. "
            "Install with: pip install pymupdf"
        )

    tmp_dir = tempfile.mkdtemp(prefix="unlimited_ocr_")

    try:
        import multiprocessing
        from concurrent.futures import ProcessPoolExecutor
        from concurrent.futures import TimeoutError as FuturesTimeout
        # Use spawn (not fork) so the child doesn't inherit torch/CUDA state
        ctx = multiprocessing.get_context("spawn")
        with ProcessPoolExecutor(max_workers=1, mp_context=ctx) as pool:
            future = pool.submit(_pdf_to_images_worker, pdf_path, tmp_dir, dpi)
            n_pages = future.result(timeout=300)
    except (FuturesTimeout, Exception) as e:
        # Subprocess died (segfault, timeout, etc.) - check if it
        # managed to write any pages before dying
        existing = sorted(
            f for f in os.listdir(tmp_dir)
            if f.endswith(".png")
        )
        if not existing:
            _cleanup_pdf_temp(tmp_dir)
            raise RuntimeError(
                f"PDF conversion failed (subprocess): {e}"
            )
        n_pages = len(existing)

    paths = sorted(
        os.path.join(tmp_dir, f)
        for f in os.listdir(tmp_dir)
        if f.endswith(".png")
    )
    return paths


def _cleanup_pdf_temp(tmp_dir: str):
    """Remove a temporary directory created by _pdf_to_images."""
    if tmp_dir and os.path.isdir(tmp_dir):
        import shutil
        with contextlib.suppress(OSError):
            shutil.rmtree(tmp_dir)


def _collect_images_from_dir(directory: str) -> list[str]:
    """Collect all image files from a directory, sorted by name."""
    paths = []
    for root, _, files in os.walk(directory):
        for name in sorted(files):
            if Path(name).suffix.lower() in IMAGE_EXTENSIONS:
                paths.append(os.path.join(root, name))
    return sorted(paths)


def is_image_file(path: str) -> bool:
    """Check whether a path refers to a supported image file."""
    return Path(path).suffix.lower() in IMAGE_EXTENSIONS


def is_pdf_file(path: str) -> bool:
    """Check whether a path refers to a PDF file."""
    return Path(path).suffix.lower() in PDF_EXTENSIONS


# Client
class UnlimitedOCRClient:
    """Client for the Unlimited-OCR inference server.

    Parameters
    ----------
    server_url : str
        Base URL of the SGLang or OpenAI-compatible server.
    model_name : str
        Model name expected by the server.
    image_mode : str
        Image preprocessing mode: ``'gundam'`` (crop, 640px) or
        ``'base'`` (no crop, 1024px).  Multi-page always uses base.
    prompt : str
        Default prompt for single-image OCR.
    multi_prompt : str
        Default prompt for multi-page OCR.
    max_retries : int
        Number of retry attempts on transient failures.
    timeout : int
        Request timeout in seconds.
    """

    def __init__(
        self,
        server_url: str = DEFAULT_SERVER_URL,
        model_name: str = DEFAULT_MODEL_NAME,
        image_mode: str = "gundam",
        prompt: str = DEFAULT_PROMPT,
        multi_prompt: str = DEFAULT_MULTI_PROMPT,
        max_retries: int = MAX_RETRIES,
        timeout: int = REQUEST_TIMEOUT,
    ):
        self.server_url = server_url.rstrip("/")
        self.model_name = model_name
        self.image_mode = image_mode
        self.prompt = prompt
        self.multi_prompt = multi_prompt
        self.max_retries = max_retries
        self.timeout = timeout
        self.backend_name = "unlimited-ocr"

    @classmethod
    def deepseek_ocr2(cls, server_url: str = DEFAULT_SERVER_URL, **kwargs):
        """Create a client configured for DeepSeek-OCR-2.

        DeepSeek-OCR-2 uses the same OpenAI-compatible API as
        Unlimited-OCR when served via vLLM, with slightly different
        defaults (768px images, grounding prompt).

        Parameters
        ----------
        server_url : str
            URL of the vLLM server running DeepSeek-OCR-2.
        **kwargs
            Forwarded to the constructor.
        """
        defaults = {
            "model_name": "DeepSeek-OCR-2",
            "image_mode": "gundam",
            "prompt": "<image>\n<|grounding|>Convert the document to markdown.",
            "multi_prompt": "<image>\n<|grounding|>Convert the document to markdown.",
        }
        defaults.update(kwargs)
        inst = cls(server_url=server_url, **defaults)
        inst.backend_name = "deepseek-ocr-2"
        return inst

    @classmethod
    def deepseek_ocr(cls, server_url: str = DEFAULT_SERVER_URL, **kwargs):
        """Create a client configured for DeepSeek-OCR (v1).

        Parameters
        ----------
        server_url : str
            URL of the vLLM server running DeepSeek-OCR.
        **kwargs
            Forwarded to the constructor.
        """
        defaults = {
            "model_name": "DeepSeek-OCR",
            "image_mode": "gundam",
            "prompt": "<image>\n<|grounding|>Convert the document to markdown.",
            "multi_prompt": "<image>\n<|grounding|>Convert the document to markdown.",
        }
        defaults.update(kwargs)
        inst = cls(server_url=server_url, **defaults)
        inst.backend_name = "deepseek-ocr"
        return inst

    # Health check
    def is_available(self) -> bool:
        """Check whether the OCR server is reachable and healthy."""
        try:
            import requests
            resp = requests.get(
                f"{self.server_url}/health", timeout=5,
            )
            return resp.status_code == 200
        except Exception:
            return False

    # Single-image OCR
    def ocr_image(
        self,
        image_path: str,
        prompt: str | None = None,
        image_mode: str | None = None,
    ) -> OCRResult:
        """Run OCR on a single image.

        Parameters
        ----------
        image_path : str
            Path to the image file.
        prompt : str, optional
            Override the default prompt.
        image_mode : str, optional
            Override the default image mode.

        Returns
        -------
        OCRResult
        """
        import requests

        prompt = prompt or self.prompt
        mode = image_mode or self.image_mode
        ngram_window = DEFAULT_NGRAM_WINDOW

        content = [
            {"type": "text", "text": prompt},
            _encode_image(image_path),
        ]
        payload = self._build_payload(content, mode, ngram_window)

        start = time.time()
        text, tokens = self._send_request(requests, payload, image_path)
        elapsed = time.time() - start

        return OCRResult(
            text=text,
            source=image_path,
            page=0,
            tokens=tokens,
            elapsed=elapsed,
        )

    # Multi-page OCR
    def ocr_images(
        self,
        image_paths: Sequence[str],
        prompt: str | None = None,
    ) -> OCRBatchResult:
        """Run OCR on multiple images as a single multi-page request.

        Parameters
        ----------
        image_paths : sequence of str
            Paths to image files, in order.
        prompt : str, optional
            Override the default multi-page prompt.

        Returns
        -------
        OCRBatchResult
        """
        import requests

        prompt = prompt or self.multi_prompt
        ngram_window = DEFAULT_NGRAM_WINDOW_MULTI

        content = [{"type": "text", "text": prompt}]
        for img in image_paths:
            content.append(_encode_image(img))

        payload = self._build_payload(content, "base", ngram_window)

        start = time.time()
        text, tokens = self._send_request(
            requests, payload, str(image_paths),
        )
        elapsed = time.time() - start

        # Split into per-page results heuristically
        pages = self._split_pages(text, image_paths)

        return OCRBatchResult(
            pages=pages,
            source=str(image_paths[0]) if image_paths else "",
            total_tokens=tokens,
            total_elapsed=elapsed,
        )

    # PDF OCR
    def ocr_pdf(
        self,
        pdf_path: str,
        dpi: int = 300,
        prompt: str | None = None,
    ) -> OCRBatchResult:
        """Run OCR on a PDF document.

        Converts pages to images, then runs multi-page OCR.

        Parameters
        ----------
        pdf_path : str
            Path to the PDF file.
        dpi : int
            Resolution for page rasterization.
        prompt : str, optional
            Override the default multi-page prompt.

        Returns
        -------
        OCRBatchResult
        """
        image_paths = _pdf_to_images(pdf_path, dpi=dpi)
        try:
            result = self.ocr_images(image_paths, prompt=prompt)
            result.source = pdf_path
            return result
        finally:
            if image_paths:
                _cleanup_pdf_temp(os.path.dirname(image_paths[0]))

    # Directory OCR
    def ocr_directory(
        self,
        directory: str,
        prompt: str | None = None,
    ) -> OCRBatchResult:
        """Run OCR on all images in a directory.

        Parameters
        ----------
        directory : str
            Path to a directory containing image files.
        prompt : str, optional
            Override the default prompt.

        Returns
        -------
        OCRBatchResult
        """
        image_paths = _collect_images_from_dir(directory)
        if not image_paths:
            return OCRBatchResult(source=directory)
        return self.ocr_images(image_paths, prompt=prompt)

    # Internals
    def _build_payload(
        self,
        content: list[dict],
        image_mode: str,
        ngram_window: int,
    ) -> dict:
        """Build the request payload."""
        payload: dict[str, Any] = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": content}],
            "temperature": DEFAULT_TEMPERATURE,
            "skip_special_tokens": False,
            "stream": True,
            "images_config": {"image_mode": image_mode},
        }
        if DEFAULT_NGRAM_SIZE > 0 and ngram_window > 0:
            # The ngram processor is only needed if sglang is the backend.
            # For generic OpenAI-compatible servers it's ignored gracefully.
            try:
                from sglang.srt.sampling.custom_logit_processor import (
                    DeepseekOCRNoRepeatNGramLogitProcessor,
                )
                payload["custom_logit_processor"] = (
                    DeepseekOCRNoRepeatNGramLogitProcessor.to_str()
                )
            except ImportError:
                pass
            payload["custom_params"] = {
                "ngram_size": DEFAULT_NGRAM_SIZE,
                "window_size": ngram_window,
            }
        return payload

    def _send_request(
        self,
        requests_mod,
        payload: dict,
        source_label: str,
    ) -> tuple[str, int]:
        """Send the request with retries and collect the streamed response."""
        for attempt in range(self.max_retries):
            try:
                resp = requests_mod.post(
                    f"{self.server_url}/v1/chat/completions",
                    headers={"Content-Type": "application/json"},
                    data=json.dumps(payload),
                    timeout=self.timeout,
                    stream=True,
                )
                if resp.status_code == 502 and attempt < self.max_retries - 1:
                    time.sleep(3 * (attempt + 1))
                    continue
                resp.raise_for_status()
                return self._collect_stream(resp)
            except Exception as e:
                if attempt < self.max_retries - 1:
                    logger.warning(
                        "OCR request retry %d/%d for %s: %s",
                        attempt + 1, self.max_retries, source_label, e,
                    )
                    time.sleep(3 * (attempt + 1))
                    continue
                logger.error(
                    "OCR request failed for %s: %s", source_label, e,
                )
                raise

        return "", 0

    @staticmethod
    def _collect_stream(resp) -> tuple[str, int]:
        """Collect a streaming response into text and token count."""
        chunks: list[str] = []
        token_count = 0
        for raw_line in resp.iter_lines():
            if not raw_line:
                continue
            line = (
                raw_line.decode("utf-8")
                if isinstance(raw_line, bytes)
                else raw_line
            )
            if not line.startswith("data:"):
                continue
            data = line[len("data:"):].strip()
            if data == "[DONE]":
                break
            try:
                chunk = json.loads(data)
                delta = (
                    chunk["choices"][0]
                    .get("delta", {})
                    .get("content", "")
                )
            except (json.JSONDecodeError, KeyError, IndexError):
                continue
            if delta:
                token_count += 1
                chunks.append(delta)
        return "".join(chunks), token_count

    @staticmethod
    def _split_pages(
        text: str,
        image_paths: Sequence[str],
    ) -> list[OCRResult]:
        """Heuristically split multi-page output into per-page results."""
        # Try splitting on page-break markers the model may emit
        page_pattern = re.compile(
            r'(?:---\s*page\s*\d+\s*---|'
            r'<!--\s*page\s*\d+\s*-->|'
            r'\[page\s*\d+\]|'
            r'\\newpage)',
            re.IGNORECASE,
        )
        parts = page_pattern.split(text)
        # Filter empty parts
        parts = [p.strip() for p in parts if p.strip()]

        results: list[OCRResult] = []
        for i, img in enumerate(image_paths):
            page_text = parts[i] if i < len(parts) else ""
            results.append(OCRResult(
                text=page_text,
                source=img,
                page=i + 1,
            ))
        return results


# Offline fallback
class OfflineOCRClient:
    """Fallback client that extracts text from images using
    lightweight local methods (Tesseract OCR) when the
    Unlimited-OCR server is unavailable.

    Falls back to an empty string if Tesseract is also unavailable,
    allowing the pipeline to proceed with whatever text can be
    extracted.
    """

    def __init__(self):
        self._has_tesseract = self._check_tesseract()

    @staticmethod
    def _check_tesseract() -> bool:
        try:
            import subprocess
            result = subprocess.run(
                ["tesseract", "--version"],
                capture_output=True, timeout=5,
            )
            return result.returncode == 0
        except Exception:
            return False

    def ocr_image(self, image_path: str, **kwargs) -> OCRResult:
        text = self._extract(image_path)
        return OCRResult(text=text, source=image_path, page=0)

    def ocr_pdf(self, pdf_path: str, dpi: int = 300, **kwargs) -> OCRBatchResult:
        images = _pdf_to_images(pdf_path, dpi=dpi)
        try:
            pages = []
            for i, img in enumerate(images):
                text = self._extract(img)
                pages.append(OCRResult(text=text, source=img, page=i + 1))
            return OCRBatchResult(pages=pages, source=pdf_path)
        finally:
            if images:
                _cleanup_pdf_temp(os.path.dirname(images[0]))

    def ocr_images(self, image_paths: Sequence[str], **kwargs) -> OCRBatchResult:
        pages = []
        for i, img in enumerate(image_paths):
            text = self._extract(img)
            pages.append(OCRResult(text=text, source=img, page=i + 1))
        return OCRBatchResult(
            pages=pages,
            source=str(image_paths[0]) if image_paths else "",
        )

    def ocr_directory(self, directory: str, **kwargs) -> OCRBatchResult:
        images = _collect_images_from_dir(directory)
        return self.ocr_images(images)

    def is_available(self) -> bool:
        return self._has_tesseract

    def _extract(self, image_path: str) -> str:
        if not self._has_tesseract:
            logger.warning(
                "No OCR backend available for %s; returning empty text",
                image_path,
            )
            return ""
        try:
            import subprocess
            result = subprocess.run(
                ["tesseract", image_path, "stdout"],
                capture_output=True, text=True, timeout=60,
            )
            return result.stdout.strip()
        except Exception as e:
            logger.warning("Tesseract failed for %s: %s", image_path, e)
            return ""


# PaddleOCR (free, local, CPU or GPU)
class PaddleOCRClient:
    """Client using Baidu's PaddleOCR (Apache 2.0, free, local).

    PaddleOCR runs entirely on your hardware (CPU or GPU).  No API
    key, no cloud dependency, no cost.  Supports 100+ languages,
    tables, formulas, and structured Markdown/JSON output.

    Uses ``PPStructureV3`` for document parsing (layout-aware markdown)
    and falls back to ``PaddleOCR`` for plain text extraction.

    Parameters
    ----------
    use_structure : bool
        Use PP-StructureV3 for layout-aware markdown output.
        Falls back to PaddleOCR if False or if PPStructureV3 fails.
    lang : str
        Language code (e.g. ``'en'``, ``'ch'``).
    use_gpu : bool
        Enable GPU acceleration if available.

    Requires: ``pip install paddleocr``
    """

    def __init__(
        self,
        use_structure: bool = True,
        lang: str = "en",
        use_gpu: bool = False,
    ):
        self.use_structure = use_structure
        self.lang = lang
        self.use_gpu = use_gpu
        self.backend_name = "paddleocr"
        self._engine = None

    def _get_engine(self):
        """Lazily initialize the PaddleOCR engine."""
        if self._engine is not None:
            return self._engine
        try:
            if self.use_structure:
                from paddleocr import PPStructureV3
                self._engine = PPStructureV3(
                    lang=self.lang,
                    use_doc_orientation_classify=False,
                    use_doc_unwarping=False,
                )
            else:
                from paddleocr import PaddleOCR
                self._engine = PaddleOCR(
                    lang=self.lang,
                    use_doc_orientation_classify=False,
                    use_doc_unwarping=False,
                )
        except Exception as e:
            logger.warning("PaddleOCR initialization failed: %s", e)
            self._engine = None
        return self._engine

    def is_available(self) -> bool:
        """Check whether PaddleOCR can actually initialize (not just import)."""
        try:
            # Also verify paddle itself works (catches circular import issues)
            import paddle
            import paddleocr  # noqa: F401
            _ = paddle.tensor
            return True
        except Exception:
            return False

    def ocr_image(self, image_path: str, **kwargs) -> OCRResult:
        """Run OCR on a single image."""
        start = time.time()
        text = self._run_ocr(image_path)
        elapsed = time.time() - start
        return OCRResult(text=text, source=image_path, page=0, elapsed=elapsed)

    def ocr_pdf(self, pdf_path: str, dpi: int = 300, **kwargs) -> OCRBatchResult:
        """Run OCR on a PDF (page-by-page)."""
        start = time.time()
        images = _pdf_to_images(pdf_path, dpi=dpi)
        try:
            pages = []
            for i, img in enumerate(images):
                text = self._run_ocr(img)
                pages.append(OCRResult(text=text, source=img, page=i + 1))
            elapsed = time.time() - start
            return OCRBatchResult(
                pages=pages, source=pdf_path, total_elapsed=elapsed,
            )
        finally:
            if images:
                _cleanup_pdf_temp(os.path.dirname(images[0]))

    def ocr_images(self, image_paths: Sequence[str], **kwargs) -> OCRBatchResult:
        """Run OCR on multiple images."""
        start = time.time()
        pages = []
        for i, img in enumerate(image_paths):
            text = self._run_ocr(img)
            pages.append(OCRResult(text=text, source=img, page=i + 1))
        elapsed = time.time() - start
        return OCRBatchResult(
            pages=pages,
            source=str(image_paths[0]) if image_paths else "",
            total_elapsed=elapsed,
        )

    def ocr_directory(self, directory: str, **kwargs) -> OCRBatchResult:
        images = _collect_images_from_dir(directory)
        if not images:
            return OCRBatchResult(source=directory)
        return self.ocr_images(images)

    def _run_ocr(self, image_path: str) -> str:
        """Run OCR on a single image and return markdown text."""
        engine = self._get_engine()
        if engine is None:
            raise RuntimeError("PaddleOCR engine failed to initialize")
        try:
            results = list(engine.predict(image_path))
            if not results:
                return ""

            # PPStructureV3 returns objects with markdown content
            if self.use_structure and hasattr(results[0], "markdown"):
                return results[0].markdown or ""

            # PPStructureV3 may return page-level results
            if self.use_structure:
                parts = []
                for r in results:
                    md = getattr(r, "markdown", None)
                    if md:
                        parts.append(md)
                    elif hasattr(r, "rec_texts"):
                        parts.extend(r.rec_texts)
                return "\n".join(parts)

            # Plain PaddleOCR returns detection + recognition results
            parts = []
            for r in results:
                if hasattr(r, "rec_texts"):
                    parts.extend(r.rec_texts)
                elif hasattr(r, "text"):
                    parts.append(r.text)
            return "\n".join(parts)

        except Exception as e:
            logger.warning("PaddleOCR failed for %s: %s", image_path, e)
            return ""


# GOT-OCR2.0 (free, HuggingFace transformers, GPU)
class GOTOCRClient:
    """Client using GOT-OCR2.0 via HuggingFace transformers.

    GOT-OCR2.0 (General OCR Theory) is an end-to-end OCR model
    merged into ``transformers``.  Apache 2.0 code, free weights
    on HuggingFace.  Requires a GPU for inference.

    Parameters
    ----------
    model_name : str
        HuggingFace model ID.
    device : str
        PyTorch device (``'cuda'``, ``'cpu'``).
    ocr_type : str
        ``'format'`` for structured output, ``'ocr'`` for plain text.

    Requires: ``pip install transformers torch Pillow``
    """

    def __init__(
        self,
        model_name: str = "stepfun-ai/GOT-OCR-2.0-hf",
        device: str = "cuda",
        ocr_type: str = "format",
        skip_load: bool = False,
    ):
        self.model_name = model_name
        self.device = device
        self.ocr_type = ocr_type
        self.backend_name = "got-ocr2"
        self._model = None
        self._processor = None

    def _load_model(self):
        """Lazily load the GOT-OCR2.0 model and processor from local cache."""
        if self._model is not None:
            return
        try:
            import torch
            from transformers import (
                AutoProcessor,
                GotOcr2ForConditionalGeneration,
            )
        except ImportError:
            raise ImportError(
                "GOT-OCR2.0 requires transformers and torch. "
                "Install with: make install-got-ocr"
            )

        cached = self._model_cached()
        if not cached:
            raise RuntimeError(
                f"GOT-OCR2.0 model '{self.model_name}' is not downloaded. "
                "Run: make install-got-ocr"
            )

        self._processor = AutoProcessor.from_pretrained(
            self.model_name, trust_remote_code=True,
            local_files_only=True,
        )
        self._model = GotOcr2ForConditionalGeneration.from_pretrained(
            self.model_name,
            trust_remote_code=True,
            device_map=self.device,
            local_files_only=True,
        )
        self._model.eval()

    def _model_cached(self) -> bool:
        """Check if the model weights are in the local HuggingFace cache. No network."""
        cache_dir = Path.home() / ".cache" / "huggingface" / "hub"
        model_dir_name = "models--" + self.model_name.replace("/", "--")
        model_dir = cache_dir / model_dir_name
        # Check for actual weight files, not just the directory
        if not model_dir.exists():
            return False
        snapshots = model_dir / "snapshots"
        if snapshots.exists() and any(snapshots.iterdir()):
            return True
        # Fallback: check for blobs (older cache format)
        blobs = model_dir / "blobs"
        return blobs.exists() and any(blobs.iterdir())

    def is_available(self) -> bool:
        """Check whether transformers, torch, and accelerate are importable
        AND the model weights are cached locally.

        Returns False if the model would need to be downloaded, so that
        create_ocr_client() won't silently trigger a 2 GB download as a
        fallback backend.
        """
        try:
            import accelerate  # noqa: F401
            import torch  # noqa: F401
            from transformers import GotOcr2ForConditionalGeneration  # noqa
            return self._model_cached()
        except (ImportError, Exception):
            return False

    def ocr_image(self, image_path: str, **kwargs) -> OCRResult:
        """Run OCR on a single image."""
        start = time.time()
        text = self._run_ocr(image_path)
        elapsed = time.time() - start
        return OCRResult(text=text, source=image_path, page=0, elapsed=elapsed)

    def ocr_pdf(self, pdf_path: str, dpi: int = 300, **kwargs) -> OCRBatchResult:
        """Run OCR on a PDF (page-by-page)."""
        start = time.time()
        images = _pdf_to_images(pdf_path, dpi=dpi)
        try:
            pages = []
            for i, img in enumerate(images):
                text = self._run_ocr(img)
                pages.append(OCRResult(text=text, source=img, page=i + 1))
            elapsed = time.time() - start
            return OCRBatchResult(
                pages=pages, source=pdf_path, total_elapsed=elapsed,
            )
        finally:
            if images:
                _cleanup_pdf_temp(os.path.dirname(images[0]))

    def ocr_images(self, image_paths: Sequence[str], **kwargs) -> OCRBatchResult:
        start = time.time()
        pages = []
        for i, img in enumerate(image_paths):
            text = self._run_ocr(img)
            pages.append(OCRResult(text=text, source=img, page=i + 1))
        elapsed = time.time() - start
        return OCRBatchResult(
            pages=pages,
            source=str(image_paths[0]) if image_paths else "",
            total_elapsed=elapsed,
        )

    def ocr_directory(self, directory: str, **kwargs) -> OCRBatchResult:
        images = _collect_images_from_dir(directory)
        if not images:
            return OCRBatchResult(source=directory)
        return self.ocr_images(images)

    def _run_ocr(self, image_path: str) -> str:
        """Run GOT-OCR2.0 inference on a single image."""
        self._load_model()
        try:
            from PIL import Image
            image = Image.open(image_path).convert("RGB")

            inputs = self._processor(
                image, return_tensors="pt",
                ocr_type=self.ocr_type,
            ).to(self._model.device)

            import torch
            with torch.no_grad():
                generated = self._model.generate(**inputs, max_new_tokens=4096)

            text = self._processor.batch_decode(
                generated, skip_special_tokens=True,
            )[0]
            return text.strip()

        except Exception as e:
            logger.warning("GOT-OCR2.0 failed for %s: %s", image_path, e)
            return ""


# Mistral OCR (cloud API)
class MistralOCRClient:
    """Client for Mistral's cloud-hosted OCR API.

    Uses the ``mistralai`` SDK to call ``mistral-ocr-latest``.
    No GPU required, just an API key.  Native PDF support (no
    page-to-image conversion needed).

    Parameters
    ----------
    api_key : str, optional
        Mistral API key.  Defaults to the ``MISTRAL_API_KEY``
        environment variable.
    model : str
        OCR model name.  Default: ``"mistral-ocr-latest"``.

    Requires: ``pip install mistralai``
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str = "mistral-ocr-latest",
    ):
        self.api_key = api_key or os.environ.get("MISTRAL_API_KEY", "")
        self.model = model
        self.backend_name = "mistral-ocr"
        self._client = None

    def _get_client(self):
        """Lazily initialize the Mistral SDK client."""
        if self._client is None:
            try:
                from mistralai import Mistral
            except ImportError:
                raise ImportError(
                    "The mistralai package is required for Mistral OCR. "
                    "Install with: pip install mistralai"
                )
            self._client = Mistral(api_key=self.api_key)
        return self._client

    def is_available(self) -> bool:
        """Check whether the Mistral API is reachable."""
        if not self.api_key:
            return False
        try:
            self._get_client()
            return True
        except Exception:
            return False

    # Single-image OCR
    def ocr_image(
        self,
        image_path: str,
        **kwargs,
    ) -> OCRResult:
        """Run OCR on a single image via the Mistral API."""
        start = time.time()
        document = self._make_image_document(image_path)
        response = self._process(document)
        elapsed = time.time() - start

        text = self._extract_text(response)
        return OCRResult(
            text=text,
            source=image_path,
            page=0,
            elapsed=elapsed,
        )

    # PDF OCR
    def ocr_pdf(
        self,
        pdf_path: str,
        dpi: int = 300,
        **kwargs,
    ) -> OCRBatchResult:
        """Run OCR on a PDF document via the Mistral API.

        Mistral OCR supports PDFs natively - no page-to-image
        conversion is needed.
        """
        start = time.time()
        document = self._make_pdf_document(pdf_path)
        response = self._process(document)
        elapsed = time.time() - start

        pages = self._extract_pages(response, pdf_path)
        return OCRBatchResult(
            pages=pages,
            source=pdf_path,
            total_tokens=0,
            total_elapsed=elapsed,
        )

    # Multi-image OCR
    def ocr_images(
        self,
        image_paths: Sequence[str],
        **kwargs,
    ) -> OCRBatchResult:
        """Run OCR on multiple images (processed individually)."""
        start = time.time()
        pages = []
        for i, img in enumerate(image_paths):
            result = self.ocr_image(img)
            result.page = i + 1
            pages.append(result)
        elapsed = time.time() - start

        return OCRBatchResult(
            pages=pages,
            source=str(image_paths[0]) if image_paths else "",
            total_elapsed=elapsed,
        )

    # Directory OCR
    def ocr_directory(self, directory: str, **kwargs) -> OCRBatchResult:
        """Run OCR on all images in a directory."""
        images = _collect_images_from_dir(directory)
        if not images:
            return OCRBatchResult(source=directory)
        return self.ocr_images(images)

    # Internals
    def _make_image_document(self, image_path: str) -> dict:
        """Build a Mistral OCR document spec from an image file."""
        with open(image_path, "rb") as f:
            file_content = f.read()
        ext = os.path.splitext(image_path)[1].lower().lstrip(".")
        mime = f"image/{ext}" if ext != "jpg" else "image/jpeg"
        b64 = base64.b64encode(file_content).decode("utf-8")
        return {
            "type": "image_url",
            "image_url": f"data:{mime};base64,{b64}",
        }

    def _make_pdf_document(self, pdf_path: str) -> dict:
        """Build a Mistral OCR document spec from a PDF file."""
        with open(pdf_path, "rb") as f:
            file_content = f.read()
        b64 = base64.b64encode(file_content).decode("utf-8")
        return {
            "type": "document_url",
            "document_url": f"data:application/pdf;base64,{b64}",
            "document_name": os.path.basename(pdf_path),
        }

    def _process(self, document: dict):
        """Send a document to the Mistral OCR API."""
        client = self._get_client()
        return client.ocr.process(
            model=self.model,
            document=document,
            include_image_base64=False,
        )

    @staticmethod
    def _extract_text(response) -> str:
        """Extract concatenated markdown text from a Mistral OCR response."""
        if not response or not hasattr(response, "pages"):
            return ""
        parts = []
        for page in response.pages:
            if hasattr(page, "markdown") and page.markdown:
                parts.append(page.markdown)
        return "\n\n".join(parts)

    @staticmethod
    def _extract_pages(response, source: str) -> list[OCRResult]:
        """Extract per-page results from a Mistral OCR response."""
        if not response or not hasattr(response, "pages"):
            return []
        results = []
        for page in response.pages:
            page_num = getattr(page, "index", len(results) + 1)
            text = getattr(page, "markdown", "") or ""
            results.append(OCRResult(
                text=text,
                source=source,
                page=page_num,
            ))
        return results


# Factory
def _try_backend(name, server_url=None, mistral_api_key=None, **kwargs):
    """Try to create a specific OCR backend. Returns client or None."""
    try:
        if name == "server":
            url = server_url or os.environ.get("UNLIMITED_OCR_URL", DEFAULT_SERVER_URL)
            client = UnlimitedOCRClient(server_url=url)
            return client if client.is_available() else None
        elif name == "paddleocr":
            if shutil.which("rocminfo"):
                logger.info("Skipping PaddleOCR (ROCm detected)")
                return None
            client = PaddleOCRClient(**{k: v for k, v in kwargs.items() if k in ("use_structure", "lang", "use_gpu")})
            return client if client.is_available() else None
        elif name == "mistral":
            key = mistral_api_key or os.environ.get("MISTRAL_API_KEY", "")
            if key:
                client = MistralOCRClient(api_key=key)
                return client if client.is_available() else None
        elif name in ("got-ocr", "got"):
            client = GOTOCRClient(**{k: v for k, v in kwargs.items() if k in ("model_name", "device", "ocr_type")})
            return client if client.is_available() else None
        elif name in ("offline", "tesseract"):
            return OfflineOCRClient()
    except Exception as e:
        logger.info("Backend '%s' failed: %s", name, e)
    return None


def create_ocr_client(
    server_url: str | None = None,
    mistral_api_key: str | None = None,
    prefer: str | None = None,
    **kwargs,
) -> UnlimitedOCRClient | PaddleOCRClient | MistralOCRClient | GOTOCRClient | OfflineOCRClient:
    """Create the best available OCR client.

    Default priority (override with ``prefer`` or REXGRAPH_OCR_PRIORITY env var):
        1. Self-hosted GPU server (Unlimited-OCR / DeepSeek-OCR-2)
        2. PaddleOCR (local, free, CPU or GPU)
        3. Mistral OCR cloud API (if ``MISTRAL_API_KEY`` is set)
        4. GOT-OCR2.0 via HuggingFace (if torch/transformers available)
        5. Tesseract offline fallback

    Set REXGRAPH_OCR_PRIORITY to customize:
        export REXGRAPH_OCR_PRIORITY=server,paddleocr,offline
        export REXGRAPH_OCR_PRIORITY=offline  # tesseract only

    Parameters
    ----------
    server_url : str, optional
        URL of the self-hosted OCR server.
    mistral_api_key : str, optional
        Mistral API key.
    prefer : str, optional
        Force a single backend: ``'server'``, ``'paddleocr'``, ``'mistral'``,
        ``'got-ocr'``, ``'offline'``.
    **kwargs
        Forwarded to the selected client constructor.
    """
    # Check for env var priority override
    if prefer is None:
        env_priority = os.environ.get("REXGRAPH_OCR_PRIORITY", "")
        if env_priority:
            backends = [b.strip() for b in env_priority.split(",") if b.strip()]
            for backend in backends:
                client = _try_backend(backend, server_url, mistral_api_key, **kwargs)
                if client is not None:
                    return client
            logger.warning("No backend from REXGRAPH_OCR_PRIORITY=%s available, using fallback", env_priority)
            return OfflineOCRClient()
    # Forced backend
    if prefer == "paddleocr":
        client = PaddleOCRClient(**{
            k: v for k, v in kwargs.items()
            if k in ("use_structure", "lang", "use_gpu")
        })
        logger.info("Using PaddleOCR (forced)")
        return client

    if prefer == "got-ocr":
        client = GOTOCRClient(**{
            k: v for k, v in kwargs.items()
            if k in ("model_name", "device", "ocr_type")
        })
        logger.info("Using GOT-OCR2.0 (forced)")
        return client

    if prefer == "mistral":
        key = mistral_api_key or os.environ.get("MISTRAL_API_KEY", "")
        client = MistralOCRClient(api_key=key)
        logger.info("Using Mistral OCR (forced)")
        return client

    if prefer == "offline":
        return OfflineOCRClient()

    # Auto-detect: try server first
    url = server_url or os.environ.get(
        "UNLIMITED_OCR_URL", DEFAULT_SERVER_URL,
    )
    if prefer == "server" or prefer is None:
        server_kwargs = {
            k: v for k, v in kwargs.items()
            if k in ("model_name", "image_mode", "prompt",
                     "multi_prompt", "max_retries", "timeout")
        }
        client = UnlimitedOCRClient(server_url=url, **server_kwargs)
        if client.is_available():
            logger.info("Connected to OCR server at %s", url)
            return client

        if prefer == "server":
            logger.warning("OCR server at %s not available, trying other backends", url)
            # Fall through to auto-detect chain instead of returning unavailable client

    # Try PaddleOCR (free, local) - skip on ROCm (paddle needs CUDA, segfaults on AMD)
    _skip_paddle = shutil.which("rocminfo") is not None
    if _skip_paddle:
        logger.info("Skipping PaddleOCR (ROCm detected, paddle requires CUDA)")
    else:
        try:
            paddle = PaddleOCRClient(**{
                k: v for k, v in kwargs.items()
                if k in ("use_structure", "lang", "use_gpu")
            })
            if paddle.is_available():
                logger.info("Using PaddleOCR (local, free)")
                return paddle
        except Exception as e:
            logger.info("PaddleOCR unavailable: %s", e)

    # Try Mistral cloud API
    key = mistral_api_key or os.environ.get("MISTRAL_API_KEY", "")
    if key:
        client = MistralOCRClient(api_key=key)
        if client.is_available():
            logger.info("Using Mistral OCR cloud API")
            return client

    # Try GOT-OCR2.0 (GPU, better quality for academic/math papers)
    try:
        got = GOTOCRClient(**{
            k: v for k, v in kwargs.items()
            if k in ("model_name", "device", "ocr_type")
        })
        if got.is_available():
            logger.info("Using GOT-OCR2.0 via HuggingFace")
            return got
    except Exception as e:
        logger.info("GOT-OCR unavailable: %s", e)

    # Tesseract offline (CPU fallback)
    if shutil.which("tesseract"):
        logger.info("Using tesseract (offline fallback)")
        return OfflineOCRClient()

    # Final fallback
    logger.info("No OCR backend available; using offline fallback")
    return OfflineOCRClient()
